version: '3.9'

services:
  app-spring:
    image: itgram-app-spring:0.0.1
    ports:
      - "8080:8080"
    environment:
      DB_TYPE_PROD: "psql"
      MKPLADS_HOST: "psql"
      MKPLADS_PORT: 5432
      MKPLADS_DB: "itgram_publications"
      MKPLADS_USER: "postgres"
      MKPLADS_PASS: "itgram-pass"
    depends_on:
      psql:
        condition: service_healthy
      liquibase:
        condition: service_completed_successfully

  psql:
    image: postgres
    #    volumes:
    #      - postgres_data:/var/lib/postgresql/data
    #    ports:
    #      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "itgram-pass"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "itgram_publications"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  liquibase:
    image: liquibase/liquibase
    volumes:
      - ./volumes/liquibase-psql:/liquibase/changelog
    depends_on:
      psql:
        condition: service_healthy
    command: ["--defaults-file=/liquibase/changelog/liquibase.properties", "--search-path=/liquibase/changelog", "--url=jdbc:postgresql://psql:5432/itgram_publications", "update"]

#volumes:
#  postgres_data:
