openapi: 3.0.4
info:
  title: Itgram log models
  description: Log models for logging services of itgram
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
paths: {}

components:
  schemas:
    CommonLogModel:
      title: Общая модель лога
      description: Общая модель лога для всех микросервисов системы
      type: object
      properties:
        messageTime:
          type: string
        logId:
          type: string
        source:
          type: string
        publication:
          $ref: '#/components/schemas/MkplLogModel'
        errors:
          type: array
          items:
            $ref: '#/components/schemas/ErrorLogModel'

    MkplPublicationLogModel:
      title: Модель лога для микросервиса Itgram
      type: object
      properties:
        requestId:
          type: string
        operation:
          type: string
          enum:
            - create
            - read
            - update
            - delete
            - search
            - offers
            - init
            - finish
        requestPublication:
          $ref: '#/components/schemas/AdLog'
        responsePublication:
          $ref: '#/components/schemas/AdLog'
        responsePublications:
          type: array
          items:
            $ref: '#/components/schemas/AdLog'

    ErrorLogModel:
      title: Модель лога для ошибки
      type: object
      properties:
        message:
          type: string
        field:
          type: string
        code:
          type: string
        level:
          type: string

    PublicationLog:
      title: Модель лога для объявления
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        description:
          type: string
        publicationCategory:
          type: string
        visibility:
          type: string
        ownerId:
          type: string
        permissions:
          type: array
          uniqueItems: true
          items:
            type: string